<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56949" started-at="2022-09-22T02:49:47 ICT" finished-at="2022-09-22T02:50:44 ICT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56949" started-at="2022-09-22T02:49:47 ICT" finished-at="2022-09-22T02:50:44 ICT">
      <class name="tests.testCase">
        <test-method status="PASS" signature="main()[pri:0, instance:tests.testCase@69997e9d]" name="main" is-config="true" duration-ms="18685" started-at="2022-09-22T02:49:28 ICT" finished-at="2022-09-22T02:49:47 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="createNewToDo()[pri:1, instance:tests.testCase@69997e9d]" name="createNewToDo" duration-ms="15943" started-at="2022-09-22T02:49:47 ICT" finished-at="2022-09-22T02:50:03 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewToDo -->
        <test-method status="PASS" signature="editToDo()[pri:2, instance:tests.testCase@69997e9d]" name="editToDo" duration-ms="19852" started-at="2022-09-22T02:50:03 ICT" finished-at="2022-09-22T02:50:23 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editToDo -->
        <test-method status="PASS" signature="deleteToDo()[pri:3, instance:tests.testCase@69997e9d]" name="deleteToDo" duration-ms="3689" started-at="2022-09-22T02:50:23 ICT" finished-at="2022-09-22T02:50:27 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteToDo -->
        <test-method status="FAIL" signature="ChecklistToDo()[pri:4, instance:tests.testCase@69997e9d]" name="ChecklistToDo" duration-ms="17438" started-at="2022-09-22T02:50:27 ICT" finished-at="2022-09-22T02:50:44 ICT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at tests.testCase.ChecklistToDo(testCase.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ChecklistToDo -->
        <test-method status="PASS" signature="teardowns()[pri:0, instance:tests.testCase@69997e9d]" name="teardowns" is-config="true" duration-ms="0" started-at="2022-09-22T02:50:44 ICT" finished-at="2022-09-22T02:50:44 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardowns -->
      </class> <!-- tests.testCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
